// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3vO4LnTLlzxWccp950ScoPCHtemkuD0',
    appId: '1:336043917113:android:4530a2e1e319cdf2e132e8',
    messagingSenderId: '336043917113',
    projectId: 'chat-app-mozz-test',
    storageBucket: 'chat-app-mozz-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCND7NKnFZoJkW_H9p0eKseXJIvmRRre8s',
    appId: '1:336043917113:ios:d4795757a59f8eade132e8',
    messagingSenderId: '336043917113',
    projectId: 'chat-app-mozz-test',
    storageBucket: 'chat-app-mozz-test.appspot.com',
    androidClientId: '336043917113-0crhm8cckvo10ci2eic708p7fi25hvf4.apps.googleusercontent.com',
    iosClientId: '336043917113-p5fo32mq1ghkq454su27199foq7qjbi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppMozzTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCND7NKnFZoJkW_H9p0eKseXJIvmRRre8s',
    appId: '1:336043917113:ios:ee10d055cc2d3f6fe132e8',
    messagingSenderId: '336043917113',
    projectId: 'chat-app-mozz-test',
    storageBucket: 'chat-app-mozz-test.appspot.com',
    androidClientId: '336043917113-0crhm8cckvo10ci2eic708p7fi25hvf4.apps.googleusercontent.com',
    iosClientId: '336043917113-ofn0149d4ovqv6f4t4aqp85gpnp0ru4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppMozzTest.RunnerTests',
  );
}
